/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MyTeamRouteImport } from './routes/my-team'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PlayoffsRouteImport } from './routes/playoffs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as ApiPublicNflScheduleRouteImport } from './routes/api/public/nfl-schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamRoute = MyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayoffsRoute = PlayoffsRouteImport.update({
  id: '/playoffs',
  path: '/playoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNflScheduleRoute = ApiPublicNflScheduleRouteImport.update({
  id: '/api/public/nfl-schedule',
  path: '/api/public/nfl-schedule',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/my-team': typeof MyTeamRoute
  '/players': typeof PlayersRoute
  '/playoffs': typeof PlayoffsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/trades': typeof TradesRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/public/nfl-schedule': typeof ApiPublicNflScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/my-team': typeof MyTeamRoute
  '/players': typeof PlayersRoute
  '/playoffs': typeof PlayoffsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/trades': typeof TradesRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/public/nfl-schedule': typeof ApiPublicNflScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/my-team': typeof MyTeamRoute
  '/players': typeof PlayersRoute
  '/playoffs': typeof PlayoffsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/trades': typeof TradesRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/public/nfl-schedule': typeof ApiPublicNflScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/history'
    | '/import'
    | '/my-team'
    | '/players'
    | '/playoffs'
    | '/settings'
    | '/standings'
    | '/teams'
    | '/trades'
    | '/team/$teamId'
    | '/api/public/nfl-schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/history'
    | '/import'
    | '/my-team'
    | '/players'
    | '/playoffs'
    | '/settings'
    | '/standings'
    | '/teams'
    | '/trades'
    | '/team/$teamId'
    | '/api/public/nfl-schedule'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/history'
    | '/import'
    | '/my-team'
    | '/players'
    | '/playoffs'
    | '/settings'
    | '/standings'
    | '/teams'
    | '/trades'
    | '/team/$teamId'
    | '/api/public/nfl-schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  HistoryRoute: typeof HistoryRoute
  ImportRoute: typeof ImportRoute
  MyTeamRoute: typeof MyTeamRoute
  PlayersRoute: typeof PlayersRoute
  PlayoffsRoute: typeof PlayoffsRoute
  SettingsRoute: typeof SettingsRoute
  StandingsRoute: typeof StandingsRoute
  TeamsRoute: typeof TeamsRoute
  TradesRoute: typeof TradesRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
  ApiPublicNflScheduleRoute: typeof ApiPublicNflScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-team': {
      id: '/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof MyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playoffs': {
      id: '/playoffs'
      path: '/playoffs'
      fullPath: '/playoffs'
      preLoaderRoute: typeof PlayoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nfl-schedule': {
      id: '/api/public/nfl-schedule'
      path: '/api/public/nfl-schedule'
      fullPath: '/api/public/nfl-schedule'
      preLoaderRoute: typeof ApiPublicNflScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  HistoryRoute: HistoryRoute,
  ImportRoute: ImportRoute,
  MyTeamRoute: MyTeamRoute,
  PlayersRoute: PlayersRoute,
  PlayoffsRoute: PlayoffsRoute,
  SettingsRoute: SettingsRoute,
  StandingsRoute: StandingsRoute,
  TeamsRoute: TeamsRoute,
  TradesRoute: TradesRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
  ApiPublicNflScheduleRoute: ApiPublicNflScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
